{{- if  (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediamtx.fullname" . }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
data:
  mediamtx: |
    {{- tpl .Values.mediamtx . | nindent 4 -}}
{{- end }}