apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediamtx.fullname" . }}
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.ports }}
  ports:
    {{- range $key, $port := . }}
    {{- if $port }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "mediamtx.selectorLabels" . | nindent 4 }}
